spring:
  redis:
    host: 111.230.70.100
    port: 6379
    password: redis2019$
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gz-cdb-qlqtn6j8.sql.tencentcdb.com:63816/bing-auth?useUnicode=true&characterEncoding=utf8
    username: root
    password: BingCloud666$
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml