spring:
  cloud:
    gateway:
      routes:
        - id: bing-auth           # 网关路由到认证中心服务bing-auth
          uri: lb://bing-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: bing-upms           # 网关路由到UPMS服务bing-upms
          uri: lb://bing-upms
          predicates:
            - Path=/upms/**
          filters:
            - StripPrefix=1
