spring:
  cloud:
    gateway:
      routes:
        - id: ice-auth           # 网关路由到认证中心服务ice-auth
          uri: lb://ice-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ice-upms           # 网关路由到UPMS服务ice-upms
          uri: lb://ice-upms
          predicates:
            - Path=/upms/**
          filters:
            - StripPrefix=1
