
spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cdb-4tu4mj0t.sql.tencentcdb.com:63257/flow
    username: root
    password: Xiehuan!3
    hikari:
      max-lifetime: 1200000
flowable:
  async-executor-activate: false
  database-schema-update: true
server:
  port: 8888
  servlet:
   context-path: /flowable-modeler
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.xiaobingby.flow.dto